eb-name = "my-geo-app"
eb-env-name = "my-geo-app-environment"
eb-env-solution-stack-name = "64bit Amazon Linux 2018.03 v3.4.21 running Tomcat 8.5 Java 8"
//vpc_id              = "vpc-XXXXXXXXX"
Instance_type       = "t2.small"
minsize             = 1
maxsize             = 2
/*public_subnets     = ["subnet-XXXXXXXXXX", "subnet-XXXXXXXXX"] # Service Subnet
elb_public_subnets = ["subnet-XXXXXXXXXX", "subnet-XXXXXXXXX"] # ELB Subnet*/
tier = "WebServer"